# Generated by Django 3.1.3 on 2020-11-26 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20201126_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='send_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 26, 19, 0, 15, 373797, tzinfo=utc)),
        ),
    ]
