# Generated by Django 3.1.3 on 2020-11-26 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_auto_20201126_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='send_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 26, 21, 59, 18, 777066, tzinfo=utc)),
        ),
    ]
